// src/utils/mockData.js
export const mockEvents = [
  {
    id: "event1",
    name: "Summer Music Festival",
    date: "2024-07-15",
    location: "Central Park",
    category: "Music",
    status: "active",
    totalTickets: 5000,
    ticketsSold: 3750,
    ticketPrice: 75,
    revenue: 281250,
  },
  {
    id: "event2",
    name: "Tech Innovation Conference",
    date: "2024-09-20",
    location: "Convention Center",
    category: "Technology",
    status: "active",
    totalTickets: 2000,
    ticketsSold: 1500,
    ticketPrice: 250,
    revenue: 375000,
  },
  {
    id: "event3",
    name: "Art Exhibition",
    date: "2024-06-10",
    location: "Modern Art Museum",
    category: "Arts",
    status: "completed",
    totalTickets: 1000,
    ticketsSold: 950,
    ticketPrice: 50,
    revenue: 47500,
  },
];

export const mockUserIds = {
  user1: "u001",
  user2: "u002",
  user3: "u003",
  user4: "u004",
  user5: "u005",
};

export const mockUsers = [
  {
    id: mockUserIds.user1,
    name: "John Doe",
    email: "john.doe@example.com",
    role: "Client",
    status: "active",
    registrationDate: "2024-01-15",
    lastLogin: "2024-05-20",
    totalPurchases: 3,
    totalSpent: 450,
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    contactNumber: "+1-555-123-4567",
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    purchaseHistory: [
      {
        eventName: "Summer Music Festival",
        date: "2024-05-15",
        tickets: 2,
        amount: 150,
      },
      {
        eventName: "Tech Conference",
        date: "2024-04-10",
        tickets: 1,
        amount: 250,
      },
    ],
  },
  {
    id: mockUserIds.user2,
    name: "Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    role: "Organizer",
    status: "active",
    registrationDate: "2024-02-01",
    lastLogin: "2024-06-01",
    eventsOrganized: 2,
    totalRevenue: 75000,
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    contactNumber: "+1-555-987-6543",
    address: {
      street: "456 Event Plaza",
      city: "San Francisco",
      state: "CA",
      zipCode: "94110",
    },
    eventHistory: [
      {
        eventName: "Tech Innovation Conference",
        date: "2024-05-20",
        ticketsSold: 1500,
        revenue: 375000,
      },
      {
        eventName: "Art Exhibition",
        date: "2024-03-15",
        ticketsSold: 950,
        revenue: 47500,
      },
    ],
  },
  {
    id: mockUserIds.user3,
    name: "Michael Chen",
    email: "michael.chen@example.com",
    role: "Client",
    status: "suspended",
    registrationDate: "2024-03-10",
    lastLogin: "2024-04-22",
    totalPurchases: 1,
    totalSpent: 200,
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    contactNumber: "+1-555-246-8135",
    address: {
      street: "789 Tech Road",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    purchaseHistory: [
      {
        eventName: "Tech Innovation Conference",
        date: "2024-04-20",
        tickets: 1,
        amount: 250,
      },
    ],
  },
  {
    id: mockUserIds.user4,
    name: "Sarah Thompson",
    email: "sarah.thompson@example.com",
    role: "Organizer",
    status: "active",
    registrationDate: "2024-04-05",
    lastLogin: "2024-05-30",
    eventsOrganized: 1,
    totalRevenue: 50000,
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    contactNumber: "+1-555-369-2580",
    address: {
      street: "321 Arts Lane",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    eventHistory: [
      {
        eventName: "Summer Art Festival",
        date: "2024-05-25",
        ticketsSold: 1000,
        revenue: 50000,
      },
    ],
  },
  {
    id: mockUserIds.user5,
    name: "David Kim",
    email: "david.kim@example.com",
    role: "Client",
    status: "active",
    registrationDate: "2024-05-01",
    lastLogin: "2024-05-25",
    totalPurchases: 2,
    totalSpent: 300,
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    contactNumber: "+1-555-147-2580",
    address: {
      street: "654 Innovation Drive",
      city: "Boston",
      state: "MA",
      zipCode: "02101",
    },
    purchaseHistory: [
      {
        eventName: "Summer Music Festival",
        date: "2024-05-15",
        tickets: 1,
        amount: 75,
      },
      {
        eventName: "Art Exhibition",
        date: "2024-04-10",
        tickets: 1,
        amount: 50,
      },
    ],
  },
];
export const mockTickets = [
  {
    id: "ticket1",
    eventId: "event1",
    eventName: "Summer Music Festival",
    purchaserId: "user1",
    purchaserName: "John Doe",
    quantity: 2,
    totalPrice: 150,
    purchaseDate: "2024-05-20",
    status: "confirmed",
  },
];
